### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by lfittl** [ubicloud/bdev_ubi#6]
Congrats on the exciting things being launched!

I found this repo via @fdr's [comment on HN](https://news.ycombinator.com/item?id=38651020) but realized there is no license attached.

Would be good if you could clarify if this is also licensed under the same Elastic-style license as the main ubicloud repo, or a different license. FWIW, I personally would welcome a more liberal license, so this can be used without restrictions for learning purposes.

**Comment by ozgune** [comment]
Hi @lfittl - thank you for this issue.

We're evaluating the right license for this project and we should have an update in about a month. Since bdev_ubi is related to other Ubicloud projects, we need a bit more time to think about our licenses holistically.

**Comment by pykello** [comment]
For now, we started conservatively and made it Elastic v2 licensed, we might revise this in future.

https://github.com/ubicloud/bdev_ubi/pull/7
